Single Neuron w/ 3 inputs

In [2]:
inputs = [1, 2, 3]

In [13]:
weights = [0.2, 0.8, -0.5]

In [14]:
bias = 2

In [15]:
output = (inputs[0] * weights[0] +
inputs[1] * weights[1] +
inputs[2] * weights[2] + bias)

In [16]:
print (output)

2.3


Single Neuron w/ 4 inputs: 

In [19]:
inputs = [1.0, 2.0, 3.0, 2.5];
weights = [0.2, 0.8, -0.5, 1.0];
bias = 2;
output = (inputs[0] * weights[0] +
inputs[1] * weights[1] +
inputs[2] * weights[2] + 
inputs[3] * weights[3] + bias)
print (output)



4.8


Layer of Neurons

In [21]:
inputs = [1.0, 2.0, 3.0, 2.5];

weights1 = [0.2, 0.8, -0.5, 1.0];
weights2 = [0.5, -0.91, 0.26, -0.5];
weights3 = [-0.26, -0.27, 0.17, 0.87];

bias1 = 2;
bias2 = 3;
bias3 = 0.5;

outputs = [
    #Neruon 1:
    inputs[0] * weights1[0] +
    inputs[1] * weights1[1] +
    inputs[2] * weights1[2] + 
    inputs[3] * weights1[3] + bias1,
    #Neruon 2:
    inputs[0] * weights2[0] +
    inputs[1] * weights2[1] +
    inputs[2] * weights2[2] + 
    inputs[3] * weights2[3] + bias2,
    #Neruon 3:
    inputs[0] * weights3[0] +
    inputs[1] * weights3[1] +
    inputs[2] * weights3[2] + 
    inputs[3] * weights3[3] + bias3];
print (outputs)

[4.8, 1.21, 2.385]


Looping to scale code as thing can get challenging to code using this current method. 

In [30]:
inputs = [1.0, 2.0, 3.0, 2.5];
weights = [[0.2, 0.8, -0.5, 1.0], 
          [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]];
biases = [2, 3, 0.5];

# Output of current layer
layer_outputs = []
# For each neruon
for neuron_weights, neuron_bias in zip(weights, biases):
    # Zeroed output of given neuron
    neuron_output = 0
    # For each input and weight to the neuron
    for n_input,weight in zip(inputs,neuron_weights):
        # Multiply this input by associated weight
        # and add to the neuron's output variable
        neuron_output += n_input * weight
    # add bias
    neuron_output += neuron_bias
    # Put neuron's result to the layer's output list
    layer_outputs.append(neuron_output)
print (layer_outputs)     

[4.8, 1.21, 2.385]


This does the same thing as before, just in a more dynamic and scalable way. 


Tensors, Arrays & Vectors

In [32]:
array = [[[1,5,6,2],
         [3,2,1,3]],
        [[5,2,1,2],
         [6,4,8,4]],
        [[2,8,5,3],
         [1,1,9,4]]]
#Array is a a shape of (3, 2, 4), or a 3D array. 
print (array)

[[[1, 5, 6, 2], [3, 2, 1, 3]], [[5, 2, 1, 2], [6, 4, 8, 4]], [[2, 8, 5, 3], [1, 1, 9, 4]]]


A tensor object is an object that can be represented as an array. Are all tensors JUST arrays? No, but they are represented as arrays in our code so to us they are only arrays. 

A vector in math is what we call a list in python, or a 1-dimensional array in Numpy. 

Vector math in Python: 

In [33]:
a = [1, 2, 3]
b = [2, 3, 4]

#to obtain the dot product
dot_product = a[0]* b[0] + a[1]* b[1] + a[2]* b[2]
print (dot_product)

20


Now what if we called a "inputs" and b "weights"? Suddenly the dot product looks like a succint way to perform the operaitons we need and hgave arelay performed in plain python. Now we look to replicate in Numpy

In [34]:
import numpy as np
inputs = [1.0, 2.0, 3.0, 2.5];
weights = [0.2, 0.8, -0.5, 1.0];
bias = 2;

output = np.dot(weights, inputs) + bias
print (output)


4.8


Calculating the output of a layer of 3 neurons in numpy via 2d array

In [35]:
import numpy as np
inputs = [1.0, 2.0, 3.0, 2.5];
weights = [[0.2, 0.8, -0.5, 1.0], 
          [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]];
biases = [2, 3, 0.5];
layer_outputs = np.dot(weights, inputs) + biases
print (layer_outputs)

[4.8   1.21  2.385]


To scale, nueral networks tend to recived data in batches. So far the input data has been one sample. This can be scaled into a batch of data, taking the 1d array of input into a 2d array

This then takes the dot product that we have been using, and transformes it into a matrix product & we should also be aware of transpositions

In [40]:
import numpy as np 
a = [1,2,3]
b = [2,3,4]
print (np.dot(a,b))

a = np.array([a])
b = np.array([b]).T
print (np.dot(a,b))
#Same result of the dot product, but performed on matrices and returning a matrix


20
[[20]]


In [44]:
#Full code up to this point

inputs = [[1.0, 2.0, 3.0, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]];
weights = [[0.2, 0.8, -0.5, 1.0], 
          [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]];
biases = [2, 3, 0.5];

outputs = np.dot(inputs, np.array(weights).T) + biases

print(outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
